// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SchemaDriftDetector.Storage.Context;

#nullable disable

namespace SchemaDriftDetector.Migrations
{
    [DbContext(typeof(SchemaDriftDetectorDbContext))]
    partial class SchemaDriftDetectorDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.28");

            modelBuilder.Entity("SchemaDriftDetector.Storage.Entities.Deploy", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("CommitHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Environment")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Deploys");
                });

            modelBuilder.Entity("SchemaDriftDetector.Storage.Entities.DriftAlert", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("DeliveryStatus")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("DeployId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DetectedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EndpointId")
                        .HasColumnType("TEXT");

                    b.Property<string>("FieldPath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("RetryCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DeployId");

                    b.HasIndex("EndpointId");

                    b.ToTable("DriftAlerts");
                });

            modelBuilder.Entity("SchemaDriftDetector.Storage.Entities.Endpoint", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ApiVersion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Environment")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FirstSeenAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("HttpMethod")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeprecated")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastSeenAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RouteTemplate")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RouteTemplate", "Environment")
                        .IsUnique();

                    b.ToTable("Endpoints");
                });

            modelBuilder.Entity("SchemaDriftDetector.Storage.Entities.PendingDrift", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ChangeType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ConsecutiveCount")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("EndpointId")
                        .HasColumnType("TEXT");

                    b.Property<string>("FieldPath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastDetectedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProposedSchemaJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EndpointId");

                    b.ToTable("PendingDrifts");
                });

            modelBuilder.Entity("SchemaDriftDetector.Storage.Entities.SchemaBaseline", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EndpointId")
                        .HasColumnType("TEXT");

                    b.Property<string>("SchemaJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EndpointId")
                        .IsUnique();

                    b.ToTable("SchemaBaselines");
                });

            modelBuilder.Entity("SchemaDriftDetector.Storage.Entities.SchemaVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ChangeReason")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("DeployId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EndpointId")
                        .HasColumnType("TEXT");

                    b.Property<string>("SchemaJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DeployId");

                    b.HasIndex("EndpointId");

                    b.ToTable("SchemaVersions");
                });

            modelBuilder.Entity("SchemaDriftDetector.Storage.Entities.DriftAlert", b =>
                {
                    b.HasOne("SchemaDriftDetector.Storage.Entities.Deploy", "Deploy")
                        .WithMany("DriftAlerts")
                        .HasForeignKey("DeployId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SchemaDriftDetector.Storage.Entities.Endpoint", "Endpoint")
                        .WithMany("DriftAlerts")
                        .HasForeignKey("EndpointId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Deploy");

                    b.Navigation("Endpoint");
                });

            modelBuilder.Entity("SchemaDriftDetector.Storage.Entities.PendingDrift", b =>
                {
                    b.HasOne("SchemaDriftDetector.Storage.Entities.Endpoint", "Endpoint")
                        .WithMany("PendingDrifts")
                        .HasForeignKey("EndpointId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Endpoint");
                });

            modelBuilder.Entity("SchemaDriftDetector.Storage.Entities.SchemaBaseline", b =>
                {
                    b.HasOne("SchemaDriftDetector.Storage.Entities.Endpoint", "Endpoint")
                        .WithOne("SchemaBaseline")
                        .HasForeignKey("SchemaDriftDetector.Storage.Entities.SchemaBaseline", "EndpointId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Endpoint");
                });

            modelBuilder.Entity("SchemaDriftDetector.Storage.Entities.SchemaVersion", b =>
                {
                    b.HasOne("SchemaDriftDetector.Storage.Entities.Deploy", "Deploy")
                        .WithMany("SchemaVersions")
                        .HasForeignKey("DeployId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SchemaDriftDetector.Storage.Entities.Endpoint", "Endpoint")
                        .WithMany("SchemaVersions")
                        .HasForeignKey("EndpointId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Deploy");

                    b.Navigation("Endpoint");
                });

            modelBuilder.Entity("SchemaDriftDetector.Storage.Entities.Deploy", b =>
                {
                    b.Navigation("DriftAlerts");

                    b.Navigation("SchemaVersions");
                });

            modelBuilder.Entity("SchemaDriftDetector.Storage.Entities.Endpoint", b =>
                {
                    b.Navigation("DriftAlerts");

                    b.Navigation("PendingDrifts");

                    b.Navigation("SchemaBaseline");

                    b.Navigation("SchemaVersions");
                });
#pragma warning restore 612, 618
        }
    }
}
